### ISSUE TITLE
错误解决不了 求助

### ISSUE THREAD

**Issue by madlifer** [holmesian/Typecho-AMP#10]
错误提示:
---
> 对不起, 您的主机不支持远程访问。
> 请检查 curl 扩展、allow_url_fopen和防火墙设置！
> 出错信息：Unknown Host

用的是宝塔的一键LNMP PHP版本7.0 查看了一下phpinfo 

1.allow_url_fopen没问题
---
Directive | Local Value | Master Value
-- | -- | --
allow_url_fopen | On | On

2.curl扩展 没问题
---

cURL support | enabled
-- | --
cURL Information | 7.54.1

3.Debian8x64默认防火墙设置
---
宝塔面板放行端口:

编号 | 行为 | 状态? | 添加时间 | 说明 | 操作
-- | -- | -- | -- | -- | --
6 | 放行端口:[443] | 正常 | 2018-03-29 10:33:39 | HTTPS | 删除
5 | 放行端口:[22] | 正常 | 0000-00-00 00:00:00 | SSH远程管理服务 | 删除
4 | 放行端口:[21] | 正常 | 0000-00-00 00:00:00 | FTP服务 | 删除
3 | 放行端口:[8888] | 正常 | 0000-00-00 00:00:00 | WEB面板 | 删除
2 | 放行端口:[80] | 正常 | 0000-00-00 00:00:00 | 网站默认端口

如何解决?

**Comment by FutureApple** [comment]
dns为1.1.1.1  防火墙没问题，没有拦截记录
