### ISSUE TITLE
数据库不支持pgsql 

### ISSUE THREAD

**Issue by Lvmoo** [holmesian/Typecho-AMP#12]
数据库不支持pgsql ，插件无法启用。
请问大佬是否有支持pgsql的打算？

**Comment by holmesian** [comment]
最新的版本也会报错？

**Comment by Lvmoo** [comment]
QAQ 是的呀，现在提交时候会有报错
function unix_timestamp(timestamp with time zone) does not exist
貌似还是pgsql的锅？
