### ISSUE TITLE
增加浏览器上方的ico设置入口

### ISSUE THREAD

**Issue by Cydianrice** [holmesian/Typecho-AMP#14]
<link rel="shortcut icon" href="https://xxxxx">

并且请支持 base64 的图片链接，减少并发。

另：建议添加选项，是否可以纯HTTPS模式。
即：增加HTTPS头，避免https引用http，然后报错。
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />

**Comment by Cydianrice** [comment]
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />`

这个是建议添加的meta头

**Comment by Cydianrice** [comment]
`<link rel="shortcut icon" href="xxxxx">`

**Comment by Cydianrice** [comment]
3. 建议将 MIP/AMP推送接口调用地址 分开。 百度的MIP和AMP是独立推送的

**Comment by Cydianrice** [comment]
好的

**Comment by Cydianrice** [comment]
我的AMP/MIP推送好像不成功

**Comment by holmesian** [comment]
你指的是新发布文章的自动推送，还是指“AMP/MIP自动提交”页面中的提交推送？

**Comment by holmesian** [comment]
请更新到v0.7.0，新发布文章不推送的问题解决了。
