### ISSUE TITLE
谷歌提示/amp错误的问题

### ISSUE THREAD

**Issue by ttsunboy** [holmesian/Typecho-AMP#15]
谷歌提示/amp页面错误（也确实提示页面不存在），如何可以把/ampindex更换为/amp？还是说可以直接无视这个问题？

**Comment by holmesian** [comment]
没能理解是什么页面错误。

1、用的是否是最新版插件？
2、请完善页面错误的详细描述，最好能将谷歌提示的错误原始内容贴上来。

我刚看了一下我的博客是没问题的。

<img width="1256" alt="screen shot 2018-09-01 at 9 40 49 am" src="https://user-images.githubusercontent.com/1128377/44941182-2d9c8980-adcb-11e8-8182-53cb16c59fad.png">

**Comment by ttsunboy** [comment]
问题就是这样的
![1][https://public-yi.oss-cn-beijing.aliyuncs.com/img/Screenshot_2018-09-01-16-53-26-783_com.chrome.canary.png]
![2][https://public-yi.oss-cn-beijing.aliyuncs.com/img/Screenshot_2018-09-01-16-53-30-593_com.chrome.canary.png]

**Comment by holmesian** [comment]
先尝试在工具栏里标记为已修复，过一段时间再看看吧。

**Comment by ttsunboy** [comment]
棒。提示修复了
