### ISSUE TITLE
h5页的head输出错误

### ISSUE THREAD

**Issue by ShangJixin** [holmesian/Typecho-AMP#16]
```html
<link rel="amphtml" href="https://www.jimoe.cn/amp/xiongzhanghao-page-edit">
<link rel="miphtml" href="https://www.jimoe.cn/mip/xiongzhanghao-page-edit">
```
缺失.html

**Comment by ShangJixin** [comment]
刚刚我对我现在安装的做了如下更改，但我知道这种更改无法适用于全部博客。另这个插件没有对后缀进行判断，导致访问xxxxx.html和访问xxxxx.suiyi是相同的结果，望修复
https://github.com/holmesian/Typecho-AMP/blob/1108e2521f5213138503285a323807b39d9ef429/Action.php#L46
```php
$ampurl = "\n<link rel=\"amphtml\" href=\"{$fullURL}.html\">\n";
```
https://github.com/holmesian/Typecho-AMP/blob/1108e2521f5213138503285a323807b39d9ef429/Action.php#L48
```php
$mipurl = "<link rel=\"miphtml\" href=\"{$fullURL}.html\">\n";
```

**Comment by holmesian** [comment]
其实我的本意就是忽略后缀的，过去搜索引擎对静态内容有所偏爱，所以用 Rewrite 做伪静态很流行，现在的搜索引擎对 URL 后缀已经不再敏感了，所以不用刻意处理后缀。


后缀是可以限制一下，等我有空在这里加个判断。

https://github.com/holmesian/Typecho-AMP/blob/1108e2521f5213138503285a323807b39d9ef429/Action.php#L296
