### ISSUE TITLE
推送失败

### ISSUE THREAD

**Issue by ss7247** [holmesian/Typecho-AMP#17]
![_20181018112108](https://user-images.githubusercontent.com/9480946/47129544-3b996180-d2c8-11e8-8e0d-05f494ef08bf.png)

**Comment by holmesian** [comment]
![notice](https://user-images.githubusercontent.com/1128377/47200589-58f22c80-d3a9-11e8-82d0-ff58f9e3db2a.png)

not_same_site 表示你的熊掌号使用的域名与你推送的域名不一致。
