### ISSUE TITLE
Sitemap的生成需要做一下处理，当数据量过大，就会内存不足

### ISSUE THREAD

**Issue by Moidea** [holmesian/Typecho-AMP#19]
如题，Sitemap的生成最好能限制数量或者对Sitemap进行分页处理，否则内容过多就会内存不足而出错，当然应付日常博客几乎没有什么问题，在文章数目多的情况下还是有影响的，报错参考：大概6万左右文章

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

**Comment by htmlwebsites** [comment]
似乎还是有问题？
数据量过大时可以站点地图分页，参考：https://github.com/invelop/Typecho-HPSitemap
