### ISSUE TITLE
提交错误，不知道是什么原因

### ISSUE THREAD

**Issue by MomentDerek** [holmesian/Typecho-AMP#22]
错误提示：Array ( [remain] => 5000000 [success] => 0 [not_same_site] => Array ( [0] => https://momincong.xyz/index.php/amp/30 [1] => https://momincong.xyz/index.php/amp/28 [2] => https://momincong.xyz/index.php/amp/19 [3] => https://momincong.xyz/index.php/amp/17 [4] => https://momincong.xyz/index.php/amp/13 [5] => https://momincong.xyz/index.php/amp/12 [6] => https://momincong.xyz/index.php/amp/9 [7] => https://momincong.xyz/index.php/amp/7 [8] => https://momincong.xyz/index.php/amp/6 [9] => https://momincong.xyz/index.php/amp/5 [10] => https://momincong.xyz/index.php/amp/3 ) )

**Comment by holmesian** [comment]
not_same_site   跟这个情况一样

https://github.com/holmesian/Typecho-AMP/issues/17

**Comment by holmesian** [comment]
不一定要绑定熊掌号，你这个问题是由于提交的URL中的域名和你百度账号绑定的域名不匹配导致的。
