### ISSUE TITLE
php慢日志超时

### ISSUE THREAD

**Issue by 64611187** [holmesian/Typecho-AMP#23]
日志如下
php版本7.1
`plugins/AMP/Action.php:504
[0x00007f1c22613c00] {closure}() 
plugins/AMP/Action.php:513
[0x00007f1c22613b80] preg_replace_callback() 
plugins/AMP/Action.php:513
[0x00007f1c22613af0] IMGsize() 
plugins/AMP/Action.php:478
[0x00007f1c226139b0] AMPInit() 
plugins/AMP/Action.php:202
[0x00007f1c22613410] AMPpage() `
如果不 开缓存经常502

**Comment by holmesian** [comment]
这应该是用getimagesize函数获取远程图片尺寸时出错导致的，这是由于文章里引用了远程图片且你的服务器访问无法远程图片或者访问很慢导致的。

建议更换图床或图片本地化。

**Comment by 64611187** [comment]
数据库缓存bug
/amp/579
/amp/579.html
/amp/579.html.cn
/amp/579.html.cn.2
好像后缀怎么加都能缓存
还有数据库内容
<link rel="canonical" href="https://www.000.com/archives/256.html"/>
href会被缓存为cdn的CNAME域名如下
<link rel="canonical" href="https://www.000.com.cdn.dnsv1.com /archives/256.html"/>

**Comment by holmesian** [comment]
为了兼容奇奇怪怪的自定义路径，只能这样做兼容了。😂
