### ISSUE TITLE
win2012 推送时出现

### ISSUE THREAD

**Issue by jsh20999** [holmesian/Typecho-AMP#24]
对不起, 您的主机不支持远程访问。
请检查 curl 扩展、allow_url_fopen和防火墙设置！
出错信息：Unknown Host 

curl 扩展 已经开启并测试正常，
allow_url_fopen php.ini 已经开启

请教防火墙如何设置？

**Comment by holmesian** [comment]
这是php进程无法解析导致的，首先在phpinfo里确认curl 扩展、allow_url_fopen是否打开，然后在防火墙里放行php对外访问。

**Comment by jsh20999** [comment]
AMP MIP 能正常推送，熊掌号推送失败，目前
