### ISSUE TITLE
提交失败

### ISSUE THREAD

**Issue by yixiaip** [holmesian/Typecho-AMP#28]
错误提示：Array ( [error] => 401 [message] => token is invalid )
token我填的是对的

**Comment by holmesian** [comment]
再检查一下token吧，我刚测试了是没问题的。

**Comment by huiji1** [comment]
错误提示：Array ( [error] => 401 [message] => appid is invalid )

**Comment by holmesian** [comment]
> 错误提示：Array ( [error] => 401 [message] => appid is invalid )

提示很清楚了，appid 填错了。

**Comment by holmesian** [comment]
更新一下，可能是因为 appid 参数头尾有空格导致的。
