### ISSUE TITLE
插件很不错，希望可以加入熊掌号的页面改造功能

### ISSUE THREAD

**Issue by mingyue2017** [holmesian/Typecho-AMP#3]
具体可参考：[百度熊掌号页面改造](http://ziyuan.baidu.com/xzh/home/index)

**Comment by holmesian** [comment]
不是很想用需要运营者手持身份证照片的封闭内容推介服务。

见谅～

**Comment by mingyue2017** [comment]
熊掌号不是自媒体平台，那是百家号，熊掌号是给原创网站提供原创保护和收录建库以及搜索结果结构化展示的！
