### ISSUE TITLE
在内容页的顶部出现这个是怎么回事？

### ISSUE THREAD

**Issue by z1y1m1** [holmesian/Typecho-AMP#36]
你好，我在使用过程中出现这个问题，每页的顶部出现：

`
<br />
  | <b>Notice</b>:  Undefined offset: 4 in <b>/XXXXXXXXXX/usr/plugins/AMP/Action.php</b> on line <b>528</b><br />
`

是怎么回事呢，望解答，感激不尽

**Comment by holmesian** [comment]
V0.7.5.2版的这个位置是闭合img标签功能函数，看了一下我当时实现的方法存在问题，当你的文章里有多个重复的未闭合img标签时会触发这个问题，我更新一下。
