### ISSUE TITLE
百度缓存的mip不显示防盗链图片

### ISSUE THREAD

**Issue by oyh196** [holmesian/Typecho-AMP#38]
我已经把百度和mip缓存域名加入了白名单，还是不显示图片，求解决！

**Comment by holmesian** [comment]
没能理解你描述的问题。。。

**Comment by oyh196** [comment]
![QQ截图20200412211342](https://user-images.githubusercontent.com/47714051/79069672-a16e7a00-7d02-11ea-9507-304349a5f5eb.png)
这是我博客百度缓存的mip页面，图片不显示！
地址：https://m.baidu.com/ala/c/s/www.blogbig.cn/mip/yjmc.html
图片是用的腾讯云oss，开启了防盗链，但是已经把百度和mip缓存域名加入了白名单。
不知道是什么问题不显示图片。

**Comment by holmesian** [comment]
看上去是 MIP 没能成功缓存你的图片。

你测试下把腾讯 COS 的防盗链关闭并允许 referer 为空，再把 Access-Control-Allow-Origin 改为 * 的情况下图片呢个能否显示。

如果可以的话就是防盗链设置的问题，你添加的白名单域名可能不对或不全。

**Comment by oyh196** [comment]
允许空referer就可以用显示了，谢谢！
