### ISSUE TITLE
插件的熊掌号识别ID和熊掌号准入密钥无法通过链接获取

### ISSUE THREAD

**Issue by heidongwang** [holmesian/Typecho-AMP#39]
您好，作者。
        我下载安装你的插件，但是无法得到熊掌号识别ID和熊掌号准入密钥配置参数。通过搜索得知，百度下架熊掌号，改为熊掌ID，是否意味着此功能不再适用？望解答下，谢谢。

**Comment by holmesian** [comment]
查了一下，熊掌号已经下线了，原来的实时提交和天级提交功能于5月18日已经停用，现在改成了 快速收录  和 普通收录 两种形式，提交的地址发生了变化。我稍后就更新一下插件，恢复一下相关的自动提交功能。

PS：原来熊掌ID绑定的站点可以选择一个继承提交权益，快速收录的默认提交配额为10，普通收录每日至多提交10万条。
