### ISSUE TITLE
0.7.6.3	版本AMP首页不输出

### ISSUE THREAD

**Issue by gzlearm** [holmesian/Typecho-AMP#44]
0.7.6.3
更新版本后发现amp首页失效

**Comment by holmesian** [comment]
是卸载插件之后重新安装的么？

我这里没有复现这个问题。

**Comment by gzlearm** [comment]
> 是卸载插件之后重新安装的么？
> 
> 我这里没有复现这个问题。

 是的，已经卸载再覆盖安装的，AMP首页获取不到内容，目前已放弃

**Comment by holmesian** [comment]
> > 是卸载插件之后重新安装的么？
> > 我这里没有复现这个问题。
> 
> 是的，已经卸载再覆盖安装的，AMP首页获取不到内容，目前已放弃

是否文章默认设置了访问权限或者密码？
