### ISSUE TITLE
TYPECHO1.2/PHP7.4 环境下无法启用插件

### ISSUE THREAD

**Issue by MBRjun** [holmesian/Typecho-AMP#45]
报错一个500 SERVER ERROR
麻烦适配一下PHP74

**Comment by holmesian** [comment]
有具体的php错误提示么？

7.3是正常的，等我有空搭个7.4环境试试

**Comment by Vndroid** [comment]
已使用 PHP 7.4 多日，无此问题，建议提供 PHP 的 error.log 以供排查。
