### ISSUE TITLE
AMP 页面中的图片缩放问题

### ISSUE THREAD

**Issue by Vndroid** [holmesian/Typecho-AMP#49]
在 AMP 页面中图片会被强制缩放，改变比例后导致图片拉伸。

比如页面 [图片被缩放](https://www.vvave.net/amp/start-use-git-tools-on-computers-running-the-windows-operating-system.html)

可见图片已经被严重拉伸，是否有更好的解决方式？

最好能进行等比例缩放

**Comment by holmesian** [comment]
检查一下你的服务器能否执行 getimagesize 函数。

缩放的问题之前已经通过[这个函数](https://github.com/holmesian/Typecho-AMP/blob/407851b75bef8a7a1b5f08ea994fa5fa9e7a9b33/Action.php#L555)已经解决了，我这边的[效果是正常](https://holmesian.org/mip/Haproxy-distinguishes-flow-characteristics)的。

你页面中的图片用的是1200*800的默认值，说明没有正确获取到图片尺寸。

**Comment by Vndroid** [comment]
经过测试，getimagesize 是自带函数，非 GD 库的函数，按照[官网样例](https://www.php.net/manual/zh/function.getimagesize.php)

```php
<?php
$size = getimagesize("https://holmesian.org/usr/uploads/2018/03/1763261028.png");
var_dump($size);
```

服务器可正确执行，结果如下

```
array (size=6)
  0 => int 380
  1 => int 387
  2 => int 3
  3 => string 'width="380" height="387"' (length=24)
  'bits' => int 8
  'mime' => string 'image/png' (length=9)
```

PHP version: 7.4.8
PHP environment: docker container

怀疑是 PHP 7.4 的兼容问题。

**Comment by holmesian** [comment]
> 经过测试，getimagesize 是自带函数，非 GD 库的函数，按照[官网样例](https://www.php.net/manual/zh/function.getimagesize.php)
> 
> ```
> <?php
> $size = getimagesize("https://holmesian.org/usr/uploads/2018/03/1763261028.png");
> var_dump($size);
> ```
> 
> 服务器可正确执行，结果如下
> 
> ```
> array (size=6)
>   0 => int 380
>   1 => int 387
>   2 => int 3
>   3 => string 'width="380" height="387"' (length=24)
>   'bits' => int 8
>   'mime' => string 'image/png' (length=9)
> ```
> 
> PHP version: 7.4.8
> PHP environment: docker container
> 
> 怀疑是 PHP 7.4 的兼容问题，望复查。

你试着getimagesize一下 https://img2.vvave.net/view/public/200921024101.jpg，应该是服务端限制了UA之类的限制，所以获取不到图片信息。

**Comment by Vndroid** [comment]
> https://img2.vvave.net/view/public/200921024101.jpg

服务器确实做了限制，只限制了 refer ，理论上只要能获取到图片，就不会出现无法获取图片的尺寸问题，尝试去掉限制后，发现故障依旧。

临时测试页：[测试链接](https://www.vvave.net/t.php)

应该不是此问题导致的。

**Comment by holmesian** [comment]
> > https://img2.vvave.net/view/public/200921024101.jpg
> 
> 服务器确实做了限制，只限制了 refer ，理论上只要能获取到图片，就不会出现无法获取图片的尺寸问题，尝试去掉限制后，发现故障依旧。
> 
> 临时测试页：[测试链接](https://www.vvave.net/t.php)
> 
> 应该不是此问题导致的。

我这边看到你的页面已经正常了，之前你看到的故障依旧应该是缓存的原因😄

**Comment by Vndroid** [comment]
重建缓存后确实恢复了，建议增加 refer 和自定义 UA 功能，毕竟这两个是常用的访问限制手段，
