### ISSUE TITLE
访问amp文章页都提示图片路径出错

### ISSUE THREAD

**Issue by 0x401** [holmesian/Typecho-AMP#6]
`Warning: getimagesize(/images/xxx.jpg): failed to open stream: No such file or directory in /www/wwwroot/xxxxxxx/typecho/usr/plugins/AMP/Action.php on line 495`
文章用的markdown格式，图片是相对路径

**Comment by holmesian** [comment]
因为要获取图片的尺寸，所以用了getimagesize，这里我再加一个容错判断吧。
