### ISSUE TITLE
最新版启用后，还是500错误～

### ISSUE THREAD

**Issue by bojone** [holmesian/Typecho-AMP#8]
感谢作者昨天的修改，然而我今天测试还是500～激活的时候500。插件需要什么特殊配置的，比如权限之类的？

区别：前一版本，500后仍然会把AMP写入到后台的菜单中，这次500后没有把AMP写入菜单了。

**Comment by holmesian** [comment]
你用的哪个版本的PHP？  请打开详细错误提示，把具体的出错提示贴上来看看。

我这边在7.x和5.6测试都没复现，

**Comment by bojone** [comment]
Parse error: syntax error, unexpected '{' in /www/wwwroot/kexue.fm/usr/plugins/AMP/Plugin.php on line 113

**Comment by bojone** [comment]
php 5.4

**Comment by bojone** [comment]
我网上查了一下，应该是php版本的问题，finally特性是5.5才引入的。

建议注明需要的php版本～

**Comment by bojone** [comment]
我升级到php5.6了。这个问题暂时算是解决。

另外请问下，提交amp和mip都失败，提交熊掌号成功，就是amp的格式不符合规范吗？如果是的话，能只提交符合的吗？

**Comment by bojone** [comment]
我很确定接口地址没写错啊～

**Comment by holmesian** [comment]
你的环境可能不支持curl/fsockopen，或者防火墙禁止对外访问。
